# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|  
  config.vm.box = "silvestrini-ol9"
  config.vm.box_download_insecure=true   
  config.vbguest.auto_update = false
  config.vbguest.no_install  = true  
  config.vbguest.no_remote   = true 
  config.vm.network "public_network",nic_type: "virtio", ip: "192.168.0.150", netmask: "255.255.255.0", mode: "bridge",bridge:[
    "Intel(R) I211 Gigabit Network Connection",
    "MediaTek Wi-Fi 6 MT7921 Wireless LAN"
  ]  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../configs/", "/home/vagrant/configs"  
  config.vm.synced_folder "../scripts", "/home/vagrant/scripts"
  config.vm.synced_folder "../security", "/home/vagrant/security"  
  config.vm.synced_folder "../backstage", "/home/vagrant/backstage"      
  config.vm.provision "shell", name: "[SCRIPT USERDATA-OL9.SH]", path: "../scripts/userdata-ol9.sh"
end

