- name: Create directory if it doesn't exist
  command: test -d '{{ app_dir }}'
  become: true    
  register: directory_check
  ignore_errors: true

- name: Create '{{ app_dir }}' directory
  command: mkdir -p '{{ app_dir }}'
  become: true  
  when: directory_check.rc != 0

- name: Set permissions on /opt/backstage
  command: chown -R vagrant:vagrant /opt/backstage
  become: true
  
- name: Check if source directory exists
  stat:
    path: '{{ app_scaff }}'
  register: source_directory

- name: Copy skynet to /opt/backstage
  synchronize:
    src: '{{ app_scaff }}/'
    dest: '{{ app_dir }}/'
    recursive: yes  
  when: source_directory.stat.exists

- name: Find and run dos2unix
  find:
    paths: '{{ app_dir }}'
    patterns: "*.*"
  register: found_files

- name: Execute dos2unix on found files
  command: dos2unix "{{ item.path }}"
  with_items: "{{ found_files.files }}"
  no_log: true

- name: Install dependencies with Yarn
  shell: source "{{ ansible_env.HOME }}/.bashrc" && cd '{{ app_dir }}'  && yarn install && yarn cache clean
  args:    
    executable: /bin/bash
    chdir: '{{ app_dir }}'

- name: Synchronize files to '{{ app_scaff }}'
  synchronize:
    src: '{{ app_dir }}/'  # Garantir que há uma barra no final
    dest: '{{ app_scaff }}/'
    rsync_opts:
      - --exclude=node_modules
      - --exclude=dist-types
      - --exclude=.git
  
- name: Set permissions on /opt/backstage
  command: chown -R vagrant:vagrant /opt/backstage
  become: true  

- name: Kill any node processes
  command: pkill node
  become: true
  ignore_errors: true  # Assuming it's okay if no process is found

# - name: Start the application in background
#   shell: source {{ ansible_env.HOME }}/.bashrc && yarn dev > '{{ app_dir }}/yarn_dev.log' 2>&1 &
#   args:
#     chdir: '{{ app_dir }}'
#     executable: /bin/bash

# - name: Ensure Backstage starts successfully
#   block:
#     - name: Wait for Backstage Stack Up'
#       wait_for:
#         path: '{{ app_dir }}/yarn_dev.log'
#         search_regex: 'webpack compiled successfully'
#         timeout: 120  # 10 minutes

#     - name: Display success message
#       debug:
#         msg: "Backstage started successfully!"

#   rescue:
#     - name: Display failure message
#       debug:
#         msg: "Backstage did not start successfully within the given time."
