- name: Create directory if it doesn't exist
  command: test -d '{{ app_dir }}'
  become: true    
  register: directory_check
  ignore_errors: true
  no_log: true

- name: Create '{{ app_dir }}' directory
  command: mkdir -p '{{ app_dir }}'
  become: true  
  when: directory_check.rc != 0

- name: Set permissions on /opt/backstage
  command: chown -R vagrant:vagrant /opt/backstage
  become: true
  
- name: Check if source directory exists
  stat:
    path: '{{ app_scaff }}'
  register: source_directory

- name: Copy skynet to /opt/backstage
  synchronize:
    src: '{{ app_scaff }}/'
    dest: '{{ app_dir }}/'
    recursive: yes  
  when: source_directory.stat.exists

- name: Find and run dos2unix
  find:
    paths: '{{ app_dir }}'
    patterns: "*.*"
  register: found_files

- name: Execute dos2unix on found files
  command: dos2unix "{{ item.path }}"
  with_items: "{{ found_files.files }}"
  no_log: true

- name: Install dependencies
  ansible.builtin.shell: |
    yarn --cwd packages/app add @immobiliarelabs/backstage-plugin-gitlab
    yarn --cwd packages/backend add @immobiliarelabs/backstage-plugin-gitlab-backend
    yarn install
    yarn cache clean
  args:
    chdir: '{{ app_dir }}'
    executable: /bin/bash

- name: Synchronize files to '{{ app_scaff }}'
  synchronize:
    src: '{{ app_dir }}/'  # Garantir que há uma barra no final
    dest: '{{ app_scaff }}/'
    rsync_opts:
      - --exclude=node_modules
      - --exclude=dist-types
      - --exclude=.git
  
- name: Set permissions on /opt/backstage
  command: chown -R vagrant:vagrant /opt/backstage
  become: true  

- name: Kill any node processes
  command: pkill node
  become: true
  ignore_errors: true  # Assuming it's okay if no process is found

# - name: List files in app_dir
#   ansible.builtin.shell: ls -lt
#   args:
#     chdir: '{{ app_dir }}'
#     executable: /bin/bash
#   register: app_path

# - name: Display app_path
#   debug:
#     var: app_path.stdout_lines

# - name: Display app_dir
#   debug:
#     var: app_dir

- name: Start the application in background  
  ansible.builtin.shell: |
    source .env 
    LOG_LEVEL=debug yarn dev > '{{ app_dir }}/yarn_dev.log' 2>&1 &
  args:    
    executable: /bin/bash
    chdir: '{{ app_dir }}'

- name: Ensure Backstage starts successfully
  block:
    - name: Wait for Backstage Stack Up'
      wait_for:
        path: '{{ app_dir }}/yarn_dev.log'
        search_regex: 'webpack compiled successfully'
        timeout: 120  # 10 minutes

    - name: Display success message
      debug:
        msg: "Backstage started successfully!"

  rescue:
    - name: Display failure message
      debug:
        msg: "Backstage did not start successfully within the given time."
