# - name: Stop PostgreSQL service if running
#   systemd:
#     name: postgresql
#     state: stopped
#     ignore_errors: yes

# - name: Remove PostgreSQL packages
#   dnf:
#     name: "postgresql-server,postgresql-contrib"
#     state: absent

# - name: Remove PostgreSQL data directory
#   file:
#     path: /var/lib/pgsql
#     state: absent

# - name: Remove PostgreSQL configuration files
#   file:
#     path: /etc/postgresql
#     state: absent

- name: Update the repositories and install PostgreSQL and its tools
  dnf:
    name: "postgresql-server,postgresql-contrib,postgresql"
    state: present

- name: Initialize the PostgreSQL database and enable it to start on boot
  become_user: postgres
  command: postgresql-setup --initdb
  ignore_errors: true

- name: Enable PostgreSQL to start on boot
  systemd:
    name: postgresql
    enabled: yes
  
- name: Update the password for the postgres user to "backstage"
  command: sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'backstage'"

- name: Install PostgreSQL development package
  dnf:
    name: postgresql-devel
    state: present

- name: Get PostgreSQL version
  command: pg_config --version
  register: postgres_version
  changed_when: false
  
- name: Configure PostgreSQL to use "md5" authentication for "postgres" user
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version.stdout }}/main/pg_hba.conf"
    regexp: '^local\s+all\s+postgres\s+peer'
    line: 'local   all             postgres                                md5'

- name: Restart PostgreSQL service to apply the new password
  systemd:
    name: postgresql
    state: restarted
