- name: Update the repositories and install PostgreSQL and its tools
  dnf:
    name: "postgresql-server,postgresql-contrib,postgresql"
    state: present

- name: Configure PostgreSQL to use "md5" authentication for "postgres" user
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    remote_src: true

- name: Allow PostgreSQL database server to listen on all network interfaces
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    remote_src: true

- name: Enable PostgreSQL to start on boot
  systemd:
    name: postgresql
    enabled: yes

- name: Restart PostgreSQL service to apply the new password
  systemd:
    name: postgresql
    state: restarted

- name: Check if PostgreSQL is already initialized
  shell: systemctl is-active postgresql
  register: postgresql_status
  changed_when: false
  ignore_errors: true

- name: Initialize the PostgreSQL database and enable it to start on boot
  become_user: postgres
  command: postgresql-setup --initdb
  ignore_errors: true
  when: postgresql_status.stdout != "active"
  
- name: Update the password for the postgres user
  shell: "sudo -u postgres psql -c \"ALTER USER postgres PASSWORD '{{ postgres_password }}'\""
  
  ignore_errors: true