- name: Install required packages
  dnf:
    name:
      - python3-psycopg2
    state: present

- name: Check if PostgreSQL database is initialized
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pg_data

- name: Install PostgreSQL
  dnf:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs
    state: present

- name: Initialize database  
  command: /usr/bin/postgresql-setup initdb
  when: not pg_data.stat.exists

- name: Start PostgreSQL service 
  service:
    name: postgresql
    state: started  

- name: Enable PostgreSQL
  systemd:
    name: postgresql
    enabled: yes

- name: Set password for postgres user
  become: true
  shell: |
    sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';"
  when: not pg_data.stat.exists

- name: Stop PostgreSQL service  
  service:
    name: postgresql
    state: stopped
  ignore_errors: true
  when: not pg_data.stat.exists

- name: Configure PostgreSQL to use "md5" authentication for "postgres" user  
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    remote_src: true  
  when: not pg_data.stat.exists

- name: Allow PostgreSQL database server to listen on all network interfaces  
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: postgres
    group: postgres
    remote_src: true  
  when: not pg_data.stat.exists

- name: Start PostgreSQL service  
  service:
    name: postgresql
    state: started
