- name: Stop services  
  service:
    name: postgresql
    state: stopped
  ignore_errors: true

- name: Check if /var/lib/pgsql/data directory exists  
  stat:
    path: /var/lib/pgsql/data
  register: data_directory

- name: Remove /var/lib/pgsql/data directory if it exists  
  file:
    path: /var/lib/pgsql/data
    state: absent
  when: data_directory.stat.exists

- name: Install required packages
  dnf:
    name:
      - python3-psycopg2
    state: present

- name: Install PostgreSQL
  yum:
    name: postgresql-server
    state: present

- name: Initialize database
  become: true
  command: /usr/bin/postgresql-setup initdb

- name: Configure PostgreSQL to use "md5" authentication for "postgres" user  
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    remote_src: true  

- name: Allow PostgreSQL database server to listen on all network interfaces  
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: postgres
    group: postgres
    remote_src: true  

- name: Start services
  become: true
  service:
    name: postgresql
    state: started

- name: Enable Postgresql
  systemd:
    name: postgresql
    enabled: yes

- name: Set password for postgres user
  become: true
  shell: |
    sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';"
