- name: Stop services  
  service:
    name: postgresql
    state: stopped
  ignore_errors: true

- name: Uninstall PostgreSQL
  dnf:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs
    state: absent

- name: Remove PostgreSQL folders
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/pgsql
    - /var/log/pgsql
    - /etc/pgsql
  ignore_errors: true

- name: Install required packages
  dnf:
    name:
      - python3-psycopg2
    state: present

- name: Install PostgreSQL
  dnf:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs
    state: present

- name: Initialize database  
  command: /usr/bin/postgresql-setup initdb

- name: Start services  
  service:
    name: postgresql
    state: started

- name: Enable Postgresql
  systemd:
    name: postgresql
    enabled: yes

- name: Set password for postgres user
  become: true
  shell: |
    sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';"

- name: Stop services  
  service:
    name: postgresql
    state: stopped
  ignore_errors: true

- name: Configure PostgreSQL to use "md5" authentication for "postgres" user  
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    remote_src: true  

- name: Allow PostgreSQL database server to listen on all network interfaces  
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: postgres
    group: postgres
    remote_src: true  

- name: Start services  
  service:
    name: postgresql
    state: started

# - name: Set password for postgres user
#   become: true
#   shell: |
#     sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';"
